### ISSUE TITLE
Create ETU setting

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/SavageTools#2]

**Comment by herrozerro** [comment]
I'm finishing up the horror setting, I'll look at tackling this next.

**Comment by herrozerro** [comment]
ETU Changes the ranks from Novice, Seasoned, Veteran, and Heroic.  To Freshmen, Sophmore, Junior, and Senior.  Should this be handled in the setting file?  IE: Change the requirements there?

**Comment by Grauenwolf** [comment]
Look at `Core.savage-setting` for the ranks.

In theory, if you paste that into the ETU file you can change the names.

**Comment by Grauenwolf** [comment]
P.S. By "in theory" I mean that was the intention, but I never tested it.

**Comment by herrozerro** [comment]
Ah!  I see it now.  Well, let's see how this works out.

**Comment by herrozerro** [comment]
So what happens is that it just adds them.  So you get the normal ranks, plus the new ranks.  I am thinking either doing something like the remove skills attributes, or a boolean to remove override ranks, where if true clear out all of the ranks from previous books.

**Comment by Grauenwolf** [comment]
It should replace the old set entirely. I can't think of any reason to mix ranks from two different sets.

**Comment by herrozerro** [comment]
if (book.Ranks != null)
                foreach (var item in book.Ranks)
                {
                    Ranks.RemoveAll(s => s.Name == item.Name);
                    Ranks.Add(item);
                }

If the ranks were named the same it would.  But the names are different.  I might be able to tie it to experience, but then I'd have Freshman, Sophomore, Junior, Senior, and Legendary.

**Comment by herrozerro** [comment]
I'd say it could also be changed to if book.Rank != null, remove all of the ranks, and put new ranks in.  You'd have to make sure that if you add a rank in a setting you'd need to put all of them in.  You'd lose the ability to just add a single Rank, but if you're adding ranks already, just add all of them.

**Comment by Grauenwolf** [comment]
Well I did say it was untested. But you're right, it should erase the old ones if the new list isn't empty.

**Comment by herrozerro** [comment]
Ran into another issue.  Mixed ranks.  For example, if I am using ETU ranks, then we have both novice and Freshman.  Initial thoughts are that ranks should have an "Override name" where novice is always the first rank.  but the name can be overridden for display purposes.  

Or we need some kind of cross reference to match ranks by experience level.  But that runs into the issue if ranks were to have different experience levels.  

Thoughts?

This is hardcoded in HasFeature

```
switch (name)
            {
                case "Novice": return true;
                case "Seasoned": return ignoreRank || Experience >= 20;
                case "Veteran": return ignoreRank || Experience >= 40;
                case "Heroic": return ignoreRank || Experience >= 60;
                case "Legendary": return ignoreRank || Experience >= 80;
            }
```

Another idea:  Ranks could have an ordinal number as well.  Novice = 0, Seasoned= 1, etc.  then it just boils down to if you have a tank high enough.

**Comment by Grauenwolf** [comment]
Ugh. Let me think on that.

**Comment by Grauenwolf** [comment]
Did you end up working on this? If not, I'm going to give it a try.

**Comment by herrozerro** [comment]
Yeah, my branch is still out there.  It's basically stuck on that issue outlined above

**Comment by herrozerro** [comment]
I just synced my latest commit.

**Comment by Grauenwolf** [comment]
My apologies, I didn't notice the branch. I'll work on it this evening.

**Comment by Grauenwolf** [comment]
I finally have a design that I like. Took me three or four attempts, but it works now.

Thanks for your help.
